### ISSUE TITLE
YouTube Links

### ISSUE THREAD

**Issue by sugaratias** [kdeldycke/plumage#10]
Hi there, 

I am embedding a YouTube with the `pelican_youtube plugin`.  Despite specifying the width and height of the video in the `.rst` file, the video is huge, and takes up the width of the page. 

 Many thanks

**Comment by kdeldycke** [comment]
Can you try to reproduce this issue with the latest version of the theme?

**Comment by kdeldycke** [comment]
There is no evidence of the bug being reproduced since 2014. We can close this issue.
