### ISSUE TITLE
`GOOGLE_ANALYTICS_PROPERTY` should be `auto` by default

### ISSUE THREAD

**Issue by kmonsoor** [kdeldycke/plumage#15]
As https://developers.google.com/analytics/devguides/collection/analyticsjs discusses the tracking JS snippet with `auto` always, I think `GOOGLE_ANALYTICS_PROPERTY` should be set `auto` by default.

hence, https://github.com/kdeldycke/plumage/blob/master/templates/analytics.html#L7 could be:

    ga('create', 'UA-XXXXX-Y', 'auto');

if `GOOGLE_ANALYTICS_PROPERTY` is not set by the user.

**Comment by kdeldycke** [comment]
Thanks @kmonsoor for the suggestion. Fixed the issue in commit 830528b9c94a13622ba099fea76720a1b2c7e007 .

**Comment by kmonsoor** [comment]
you are welcome.
