### ISSUE TITLE
UML support Like PlantUml or Mermaid 

### ISSUE THREAD

**Issue by dbYoung** [kdeldycke/plumage#17]
Thanks to making this great theme!

and I think It would be great if there is UML support features.

If offline and limited features., needs Mermaid .

If online and full uml features, needs Plantuml.

**Comment by kdeldycke** [comment]
You're lucky, there already is a Pelican plugin for PlantUML: https://github.com/getpelican/pelican-plugins/tree/master/plantuml

No need to add any extra-code or feature to Plumage, so I'll close the issue.
