### ISSUE TITLE
Broken Tipue search (search.html not generated)

### ISSUE THREAD

**Issue by fdev31** [kdeldycke/plumage#19]
With those files at the end of my `pelicanconf.py`

```python
PLUGINS = ['tipue_search']
TIPUE_SEARCH = True
```

The html builds fine, without any warning, but when I try to search for something, running development_server:
```
 WARNING:root:Unable to find `/search.html` or variations.
```
And indeed, the template file is not processed.

**Comment by fdev31** [comment]
By looking at another project, I found the solution, perhaps it could be marked in the README, I added to the configuration file:
```python
TEMPLATE_PAGES = {
        'search.html': 'search.html',
        }
```

**Comment by kdeldycke** [comment]
Or better, do as I do on my own blog: https://github.com/kdeldycke/kevin-deldycke-blog/commit/cd4bf8d1f4c55d835d7bfe1d7233cffe48e67a8a

Whatever the solution, feel free to create a pull request to add setup instructions in the readme! :)

**Comment by fdev31** [comment]
Great !
The `DIRECT_TEMPLATES` was my first try but didn't work for me... :/
So I ended with `TEMPLATE_PAGES`, to be honest, I just started with Pelican and don't understand/know most of the configuration aspects.

By the way, I think we were together in a company called Nexedi for few months, but can't find it on your linkedIn, did you work there at all? (ok, this is highly out of topic)

**Comment by kdeldycke** [comment]
You're not mistaken, it's me! :) You'll find reference to that company by digging deeper into my LinkedIn profile. And of course I remember our time back then in Marcq-en-Barœul offices! I ticked right away when I saw your name popping up in my mails! :)

And thanks for the feedback on that Pelican config. Do not hesitate to create a pull request and add some documentation once you have sorted this out. In the mean time do you mind if I close this issue?

Oh, and if you're in Paris send me a private message and let's have a beer! ;)

**Comment by fdev31** [comment]
Great ! :)
That was fun, I still remember the smell of the beer factory ^^

I may do a quick update now just for the contribution, since I'll probably use Tinker instead (at least give it a try), I didn't like the drop of features Pelican does about Sphinx extensions.

Np to close the issue ! I'll fork & add a few words right now anyway.

Now I'm living in Germany but I go from time to time to North/Picardy or Paris, so why not ! :)
Did you get some news about some others ? I can remember a few if not everyone !

**Comment by kdeldycke** [comment]
Ah! I almost forgot about that beer factory! 😆 

And yes, we'll have all the time to talk about the past war stories around a beer. You know were to find me! 😉
