### ISSUE TITLE
proposal: icon change for section "Browse content by"

### ISSUE THREAD

**Issue by geniusupgrader** [kdeldycke/plumage#25]
The fontawesome icons in the footer in the section "Browse content by" are not really accurate.
for CATEGORIES_SAVE_AS there is this:

fa fa-tags : 
![fa-](https://user-images.githubusercontent.com/6190906/39143195-67a2e2be-472d-11e8-88b0-0659f03a22c7.png)

which is as the name suggests for tags and not for categories. And besides that it is fontawesome 4.
I would propose this (fontawesome 5) for categories:

fas fa-th:
![download 1](https://user-images.githubusercontent.com/6190906/39143279-bffc518e-472d-11e8-8caa-d3a670db45c1.png)

But first #24 needs to be merged for fontawesome 5 support...
So I'll add this to #24.

**Comment by kdeldycke** [comment]
This has been fixed in bea9e31c4be8988f74439c2ff33232c96318bb08 and #24.
