### ISSUE TITLE
Image not centered

### ISSUE THREAD

**Issue by sugaratias** [kdeldycke/plumage#9]
Greetings!

I am using the plumage theme on my website and I think it is a great theme, I like it a lot.  However, I have just embedded an image into my site using the following .rst syntax:

```
  .. image:: |filename|/images/think.png
   :height: 300px
   :width: 500 px
   :alt: alternate text
   :align: center
```

However, when the site is generated, the image is not centered on the page.  Please can you advise how I can centre the images, and why the align tag is not working. 

Many thanks.

**Comment by kdeldycke** [comment]
Issue has been stall for 6 years. We can close it now.
