### ISSUE TITLE
incorrect URL for tags

### ISSUE THREAD

**Issue by tanimislam** [kdeldycke/plumage#90]
Easiest to describe my issue. Blog is nginx-reverse-proxied wrapped. Easiest to demonstrate on outputs.

Blog article URL: https://tanimislam.ddns.net/blog/getting-pelican-youtube-to-work.html

Working category URL: "computronics" (https://tanimislam.ddns.net/blog/category/computronics.html)

Non-working tag URL: "computer-stuff" (https://tanimislam.ddns.net/tag/computer-stuff.html)

Correct tag URL: https://tanimislam.ddns.net/blog/tag/computer-stuff.html

Do not know how to fix. Are there undocumented pelicanconf settings to make this problem disappear?

**Comment by kdeldycke** [comment]
I did not tried to replicate the issue. But you can look at [my own `pelicanconf.py` settings from my blog](https://github.com/kdeldycke/kevin-deldycke-blog/blob/main/pelicanconf.py).

**Comment by kdeldycke** [comment]
Closing for lack of feedbacks in 3 years.
